### ISSUE TITLE
Minor improvement request

### ISSUE THREAD

**Issue by k1-k0** [KaizIqbal/apple_cursor#3]
Hi, @KaizIqbal 

Big thank you for make a really awesome cursors!
P.S. waited a long time for a good implementation of that cursors for HiDPI displays. 🙃

What about improvement, as I noticed, thickness of fingers on your cursor(hand1, hand2 svgs) seem to be a little thicker than on the original cursors. Can you please check this moment or is it a feature of your cursor set?🙂

**Comment by KaizIqbal** [comment]
Thanks for Review & Using this cursor theme @k1-k0.
I just **half** the **size** of the *border* for all `Hand Cursors`.Check new build [here](https://github.com/KaizIqbal/apple_cursor/actions/runs/191324699).If there are some other **issues** let me know in [#3](https://github.com/KaizIqbal/apple_cursor/issues/3). 😊

**Comment by k1-k0** [comment]
Nope, outlines are fine
I mean these sizes 🙂
<img width="379" alt="hand_2_linux" src="https://user-images.githubusercontent.com/53624520/89105586-f574aa00-d42a-11ea-830f-f9fe57578735.png">
<img width="495" alt="hand_2_mac" src="https://user-images.githubusercontent.com/53624520/89105589-f86f9a80-d42a-11ea-80d4-c5b110449de6.png">

**Comment by KaizIqbal** [comment]
Check new [dev](https://github.com/KaizIqbal/apple_cursor/tree/dev) build [here](https://github.com/KaizIqbal/apple_cursor/actions/runs/191925576).
I **tested** (attached) latest build on my machine and it works **as expected** ✨, I imagine you enjoy this **_improvement_**.

### Attachments
[Imgur](https://imgur.com/wvCMmAs)

**Comment by k1-k0** [comment]
It's exactly what I expected 🙃
_Thank you once again!_
